### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gdevenyi** [CoBrALab/optimized_antsMultivariateTemplateConstruction#1]
- [ ] expose more qbatch options
- [ ] enable multispectral image pairs for registration
- [x] optimize walltime request (see qbatch options)
- [x] figure out multi-stage override (see https://github.com/matejak/argbash/issues/13 )
- [x] add averaging affine with rigid
- [ ] add staged cleanup
- [x] single precision
- [x] (optional?) improved initial averaging using COM alignment ( see #4 )
- [x] nlin-only modelbuild
- [ ] threshold control for mask merging?
- [x] float
- [x] add preflight check for required programs
- [x] control SyN mode
- [x] control metric for arbitrary stages
- [x] verbose mode
